"""initial database

Revision ID: 5a52a52e012d
Revises: 
Create Date: 2026-07-20 01:01:35.510639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a52a52e012d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='文档文件名'),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='uploaded', nullable=False, comment='文档状态，上传中、解析中、已解析、解析失败'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='文档上传时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='文档最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False, comment='切片ID'),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='关联的文档ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='切片索引，从0开始'),
    sa.Column('content', sa.Text(), nullable=False, comment='切片内容'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='当前切片包含的token数量'),
    sa.Column('chunk_type', sa.String(length=50), nullable=False, comment='切片类型，递归或非递归切片'),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True, comment='元数据，用于存储切片相关的额外信息，JSON格式'),
    sa.Column('parent_chunk_id', sa.Integer(), nullable=True, comment='父切片ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建/更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('document_contents',
    sa.Column('id', sa.Integer(), nullable=False, comment='文档解析内容ID'),
    sa.Column('document_id', sa.Integer(), nullable=False, comment='关联的文档ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='文档解析后的完整文本'),
    sa.Column('parser_type', sa.String(length=50), nullable=False, comment='解析器类型，如OpenAI、Google Cloud等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='文档解析时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='文档解析最后更新时间'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_contents')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('documents')
    # ### end Alembic commands ###
