"""add embedding status to document chunks

Revision ID: 709eaaa4eab9
Revises: 8b2a228e827a
Create Date: 2026-07-22 05:21:13.799106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '709eaaa4eab9'
down_revision: Union[str, Sequence[str], None] = '8b2a228e827a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding_status', sa.String(length=50), server_default='pending', nullable=False, comment='向量化状态'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding_status')
    # ### end Alembic commands ###
