"""add active processing job constraint

Revision ID: e6f3637f8a6f
Revises: a0f91e66a106
Create Date: 2026-08-02 02:01:06.617932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f3637f8a6f'
down_revision: Union[str, Sequence[str], None] = 'a0f91e66a106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_processing_jobs_active_document', 'processing_jobs', ['document_id'], unique=True, sqlite_where=sa.text("status IN ('pending', 'running')"), postgresql_where=sa.text("status IN ('pending', 'running')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_processing_jobs_active_document', table_name='processing_jobs', sqlite_where=sa.text("status IN ('pending', 'running')"), postgresql_where=sa.text("status IN ('pending', 'running')"))
    # ### end Alembic commands ###
